version: '3.8'
services:
  web:
    container_name: city-bike-backend
    build: ./
    ports:
      -'8080:8080'
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: city_bike_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped