version: '3.8'
services:
  web:
    container_name: city-bike-backend
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - db
  db:
    image: postgres:14
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: city_bike_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./files:/files
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    ports:
      - "5555:5555"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:
 